# ABOUTME: Codemagic CI/CD configuration for diVine mobile app builds.
# ABOUTME: Configured for iOS and Android builds with manual triggering only.

# Steps to setup:
# 1 - Create the Codemagic project with access to the repository.
# 2 - Setup iOS publishing:
#   2.1 - https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#:~:text=Creating%20the%20App%20Store%20Connect%20API%20key
# 3 - Setup Android publishing:
#   3.1 - Code signing: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#:~:text=Generating%20a%20keystore
#   3.2 - Connect to Google Play: https://docs.codemagic.io/yaml-publishing/google-play/
# 4 - Setup emails to receive build notifications.
# 5 - Create environment variable group "zendesk_credentials" with:
#   - ZENDESK_APP_ID
#   - ZENDESK_CLIENT_ID
#   - ZENDESK_URL
# 6 - DEFAULT_ENV is configured via build inputs (dropdown) when starting a build
#   - Options: PRODUCTION, STAGING, TEST, POC
#   - Defaults to PRODUCTION for automatic builds
# 7 - Create environment variable group "proofmode_credentials" with:
#   - PROOFMODE_SIGNING_SERVER_ENDPOINT
#   - PROOFMODE_SIGNING_SERVER_TOKEN
# 8 - PUBLISH_TO_GITHUB is configured via build inputs (dropdown) when starting builds
#   - Set to YES to upload artifacts to a GitHub Release (for Zapstore / direct distribution)
#   - Defaults to NO
#   - Requires GITHUB_TOKEN in "github_credentials" environment variable group

definitions:
  environment:
    emails: &emails
      - TODO
  scripts:
    - &setup_code_signing_xcode
      name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    - &install_flutterfire
      name: Install FlutterFire CLI
      script: dart pub global activate flutterfire_cli
    - &enable_spm
      name: Enable Swift Package Manager
      script: flutter config --enable-swift-package-manager
    - &flutter_pub_get
      name: Get Flutter dependencies
      script: flutter pub get
    - &pod_install
      name: Run pod install
      script: find . -name "Podfile" -execdir pod install \;
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/mobile/android/local.properties"
    - &build_apk
      name: Build Android APK
      script: |
        flutter build apk --release --split-per-abi --build-number=$PROJECT_BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --dart-define=DEFAULT_ENV=${{ inputs.DEFAULT_ENV }} \
          --dart-define=PROOFMODE_SIGNING_SERVER_ENDPOINT=$PROOFMODE_SIGNING_SERVER_ENDPOINT \
          --dart-define=PROOFMODE_SIGNING_SERVER_TOKEN=$PROOFMODE_SIGNING_SERVER_TOKEN
    - &build_aab
      name: Build Android AAB
      script: |
        # Offset to continue from existing Google Play builds (GP has up to 108, CM at 100)
        BUILD_NUMBER=$((PROJECT_BUILD_NUMBER + 8))
        flutter build appbundle --release --build-number=$BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --dart-define=DEFAULT_ENV=${{ inputs.DEFAULT_ENV }} \
          --dart-define=PROOFMODE_SIGNING_SERVER_ENDPOINT=$PROOFMODE_SIGNING_SERVER_ENDPOINT \
          --dart-define=PROOFMODE_SIGNING_SERVER_TOKEN=$PROOFMODE_SIGNING_SERVER_TOKEN
    - &build_macos
      name: Build macOS app
      script: |
        flutter build macos --release \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --dart-define=DEFAULT_ENV=${{ inputs.DEFAULT_ENV }} \
          --dart-define=PROOFMODE_SIGNING_SERVER_ENDPOINT=$PROOFMODE_SIGNING_SERVER_ENDPOINT \
          --dart-define=PROOFMODE_SIGNING_SERVER_TOKEN=$PROOFMODE_SIGNING_SERVER_TOKEN
    - &package_macos_dmg
      name: Package macOS DMG
      script: |
        APP_PATH="build/macos/Build/Products/Release"
        APP_NAME=$(ls "$APP_PATH" | grep '\.app$' | head -1)
        DMG_NAME="diVine-macOS.dmg"
        echo "Packaging $APP_NAME as $DMG_NAME"
        hdiutil create -volname "diVine" -srcfolder "$APP_PATH/$APP_NAME" \
          -ov -format UDZO "$APP_PATH/$DMG_NAME"
    - &publish_github_release
      name: Publish to GitHub Release
      script: |
        if [ "${{ inputs.PUBLISH_TO_GITHUB }}" != "YES" ]; then
          echo "Skipping GitHub Release (PUBLISH_TO_GITHUB != YES)"
          exit 0
        fi
        VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
        TAG="$VERSION"
        echo "Publishing to GitHub Release $TAG"
        # Collect artifacts that exist for this platform
        ARTIFACTS=()
        # Android APKs
        for f in build/app/outputs/apk/release/*arm64*.apk build/app/outputs/apk/release/*armeabi*.apk; do
          [ -f "$f" ] && ARTIFACTS+=("$f")
        done
        # iOS IPA
        for f in build/ios/ipa/*.ipa; do
          [ -f "$f" ] && ARTIFACTS+=("$f")
        done
        # macOS DMG
        for f in build/macos/Build/Products/Release/*.dmg; do
          [ -f "$f" ] && ARTIFACTS+=("$f")
        done
        if [ ${#ARTIFACTS[@]} -eq 0 ]; then
          echo "No artifacts found to upload"
          exit 1
        fi
        echo "Uploading ${#ARTIFACTS[@]} artifact(s): ${ARTIFACTS[*]}"
        # If release already exists, upload assets to it; otherwise create new
        if gh release view "$TAG" --repo "$CM_REPO_SLUG" > /dev/null 2>&1; then
          echo "Release $TAG exists, uploading assets (replacing existing)"
          gh release upload "$TAG" \
            --repo "$CM_REPO_SLUG" \
            --clobber \
            "${ARTIFACTS[@]}"
        else
          echo "Creating new release $TAG"
          gh release create "$TAG" \
            --repo "$CM_REPO_SLUG" \
            --title "$TAG" \
            --prerelease \
            --generate-notes \
            "${ARTIFACTS[@]}"
        fi
    - &build_ios
      name: Build and sign iOS
      script: |
        # Offset to continue from existing manual builds
        BUILD_NUMBER=$((PROJECT_BUILD_NUMBER + 142))
        flutter build ipa --release --build-number=$BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --dart-define=DEFAULT_ENV=${{ inputs.DEFAULT_ENV }} \
          --dart-define=PROOFMODE_SIGNING_SERVER_ENDPOINT=$PROOFMODE_SIGNING_SERVER_ENDPOINT \
          --dart-define=PROOFMODE_SIGNING_SERVER_TOKEN=$PROOFMODE_SIGNING_SERVER_TOKEN \
          --export-options-plist=/Users/builder/export_options.plist
    - &upload_dsyms_to_crashlytics
      name: Upload dSYMs to Firebase Crashlytics
      script: |
        DSYM_DIR="build/ios/archive/Runner.xcarchive/dSYMs"

        if [ ! -d "$DSYM_DIR" ]; then
          echo "ERROR: dSYM directory not found at $DSYM_DIR"
          find build/ios -name "*.dSYM" -type d 2>/dev/null || true
          exit 1
        fi

        echo "Found dSYMs:"
        ls -la "$DSYM_DIR"

        # Find the Crashlytics upload-symbols tool from the SPM build
        UPLOAD_SYMBOLS=$(find "$HOME/Library/Developer/Xcode/DerivedData" -name "upload-symbols" -type f 2>/dev/null | head -1)
        if [ -z "$UPLOAD_SYMBOLS" ]; then
          UPLOAD_SYMBOLS=$(find . -path "*/FirebaseCrashlytics*" -name "upload-symbols" -type f 2>/dev/null | head -1)
        fi

        if [ -z "$UPLOAD_SYMBOLS" ]; then
          echo "ERROR: upload-symbols tool not found. Searching all locations..."
          find "$HOME" -name "upload-symbols" -type f 2>/dev/null || true
          find . -name "upload-symbols" -type f 2>/dev/null || true
          exit 1
        fi

        echo "Found upload-symbols at: $UPLOAD_SYMBOLS"
        chmod +x "$UPLOAD_SYMBOLS"

        "$UPLOAD_SYMBOLS" \
          -gsp ios/Runner/GoogleService-Info.plist \
          -p ios \
          "$DSYM_DIR"
    - &build_ios_simulator
      name: Build iOS Simulator app
      script: |
        flutter build ios --simulator \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --dart-define=DEFAULT_ENV=${{ inputs.DEFAULT_ENV }} \
          --dart-define=PROOFMODE_SIGNING_SERVER_ENDPOINT=$PROOFMODE_SIGNING_SERVER_ENDPOINT \
          --dart-define=PROOFMODE_SIGNING_SERVER_TOKEN=$PROOFMODE_SIGNING_SERVER_TOKEN
workflows:
  ios-build:
    name: iOS Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: API key for Codemagic # Setup in Codemagic UI
    inputs:
      DEFAULT_ENV:
        description: Default environment for fresh app installs
        type: choice
        default: PRODUCTION
        options:
          - PRODUCTION
          - STAGING
          - TEST
          - POC
      PUBLISH_TO_GITHUB:
        description: Upload IPA to GitHub Release (for direct distribution)
        type: choice
        default: "NO"
        options:
          - "NO"
          - "YES"
    environment:
      flutter: 3.41.1
      xcode: latest
      cocoapods: default
      groups:
        - zendesk_credentials
        - proofmode_credentials
        - github_credentials
      vars:
        BUNDLE_ID: co.openvine.app
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *setup_code_signing_xcode
      - *install_flutterfire
      - *enable_spm
      - *pod_install
      - *build_ios
      - *upload_dsyms_to_crashlytics
      - *publish_github_release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive/dSYMs/**
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        # Don't auto-distribute to any groups - we'll manually add builds to external testers
        beta_groups: []

  ios-simulator-build:
    name: iOS Simulator Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    inputs:
      DEFAULT_ENV:
        description: Default environment for fresh app installs
        type: choice
        default: PRODUCTION
        options:
          - PRODUCTION
          - STAGING
          - TEST
          - POC
    environment:
      flutter: 3.41.1
      xcode: 16.1  # Pinned to avoid FFmpeg Kit linker issues with newer Xcode
      cocoapods: default
      groups:
        - zendesk_credentials
        - proofmode_credentials
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *install_flutterfire
      - *enable_spm
      - *flutter_pub_get
      - *pod_install
      - *build_ios_simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - /tmp/xcodebuild_logs/*.log

  android-build:
    name: Android Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    inputs:
      DEFAULT_ENV:
        description: Default environment for fresh app installs
        type: choice
        default: PRODUCTION
        options:
          - PRODUCTION
          - STAGING
          - TEST
          - POC
      PUBLISH_TO_GITHUB:
        description: Create a GitHub Release with APK artifacts (for Zapstore)
        type: choice
        default: "NO"
        options:
          - "NO"
          - "YES"
    environment:
      flutter: 3.41.1
      java: 17
      groups:
        - zendesk_credentials
        - google_play_credentials
        - proofmode_credentials
        - github_credentials
      android_signing:
        - divine_keystore
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *setup_local_properties
      - *build_apk
      - *build_aab
      - *publish_github_release
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/mapping/**/mapping.txt
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  macos-build:
    name: macOS Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    inputs:
      DEFAULT_ENV:
        description: Default environment for fresh app installs
        type: choice
        default: PRODUCTION
        options:
          - PRODUCTION
          - STAGING
          - TEST
          - POC
      PUBLISH_TO_GITHUB:
        description: Upload DMG to GitHub Release (for direct distribution)
        type: choice
        default: "NO"
        options:
          - "NO"
          - "YES"
    environment:
      flutter: 3.41.1
      xcode: latest
      cocoapods: default
      groups:
        - zendesk_credentials
        - proofmode_credentials
        - github_credentials
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *install_flutterfire
      - *enable_spm
      - *flutter_pub_get
      - *pod_install
      - *build_macos
      - *package_macos_dmg
      - *publish_github_release
    artifacts:
      - build/macos/Build/Products/Release/*.dmg
      - build/macos/Build/Products/Release/*.app
